### ISSUE TITLE
executeAction is failing with invalid action id

### ISSUE THREAD

**Issue by jdurga** [realJayNay/ost-kit-php-client#2]
Hi JayNay

[2018-07-18 06:07:28] ScholoarshipKitLog.INFO: Created action {"id":"39059","name":"DistributeFunds","kind":"user_to_user","currency":"BT","amount":null,"arbitrary_amount":true,"commission_percent":"1.50","arbitrary_commission":false} []

on execution of Action, receiving below error:
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'ID '39058' is not a valid UUID.'

May be we should remove the validation of UUID for action id in 

    public function executeAction($id, $from, $to, $amount = null, $commissionPercent = null) {
        //self::validateId($id);

Your debug traces are very good and easy to locate the error. Thanks

**Comment by realJayNay** [comment]
Hi @jdurga,
Thanks for reporting the issue. It seems that I was a bit too eagerly doing client-side validations; action IDs are not UUIDs. Fixed now by reducing the client-side validation to isset.
